language: python
python: 
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "nightly" 

install:
  - pip3 install pipenv
  - pipenv install 

script:
  - python3 status.py


deploy:
   edge: true
   provider: bluemixcloudfoundry
   manifest: manifest.yml 
   username: aakandas@in.ibm.com  
   password: 17-aakankshadas-17
   organization: aakandas   
   space: aak                    #  Defaults to US South region (ng).
   on:
    branch: master  # (optional)  Overrides region setting if specified for Bluemix local installations.
